cap-collectif/ui

README.md

[Typo] Update storybook url

---

src/components/modal/Modal.tsx

Allow to manually set z-index property on modal overlay

---

src/components/multiStepModal/index.tsx

Export `useMultiStepModal`from `MultiStepModal` so i can make a multistep form

Export `useMultiStepModal`from `MultiStepModal`

---

src/components/search/Search.stories.tsx
src/components/search/Search.tsx

Mise en place du composant `Search` alors la possibilité de charger des options en async
#33
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=257)
[Storybook](https://33-async-search--60ca00d41db7ba003be931d8.chromatic.com)

[33] Search with suggestions

---

src/components/buttonQuickAction/ButtonQuickAction.stories.tsx
src/components/buttonQuickAction/ButtonQuickAction.tsx

Comme pour le bouton, je vais en avoir besoin pour les zones géo
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=281)
[Storybook](https://adds-as-to-quickaction--60ca00d41db7ba003be931d8.chromatic.com)

Adds link possibility on ButtonQuickAction

---

src/components/accordion/button/AccordionButton.tsx
src/components/inlineSelect/choice/InlineSelectChoice.tsx
src/components/modal/header/ModalHeader.tsx

Added 
```jsx
type="button"
```
to buttons to avoid Submitting forms
NA
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=302)
[Storybook](https://fix-button-types--60ca00d41db7ba003be931d8.chromatic.com)

[Fix] Add type property to buttons so they don't submit forms

---

src/components/form/input/Input.stories.tsx
src/components/form/input/Input.tsx
src/components/form/inputGroup/InputGroup.stories.tsx
src/components/form/style.ts

C'est une V1 mais je suis assez satisfait - à tester dans une PR de maj sur platform pour être sur de rien casser ⚠️ 
#30 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=323)
[Storybook](https://30-input-adds-actions--60ca00d41db7ba003be931d8.chromatic.com)

Ajout de l'action de suppression sur un input

---

src/components/accordion/item/AccordionItem.tsx

fix le background du compo `AccordionItem`

fix accordion bg

---

src/components/form/inputGroup/InputGroup.stories.tsx
src/components/form/inputGroup/InputGroup.style.tsx

Besoin pour le compo Date avec heure (déjà prêt)
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=337)
[Storybook](https://adds-hour-to-inputgroup--60ca00d41db7ba003be931d8.chromatic.com)

Adds HourInput on InputGroup example + styles

---

src/components/modal/Modal.tsx

Bug des modales sur ipad, je tente un truc, dans tous les cas c'est un prop optionnel

Add forceDialogToFalse property in Modal

---

.github/workflows/chromatic.yml

Ca build plus, on force node à 16 (17 marche pas non plus)
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=346)
[Storybook](https://fix-chromatic-push--60ca00d41db7ba003be931d8.chromatic.com)

test w node 16

---

src/components/form/colorPicker/ColorPicker.tsx
src/components/form/input/Input.stories.tsx
src/components/form/input/Input.tsx
src/components/form/inputGroup/InputGroup.stories.tsx
src/components/form/inputGroup/InputGroup.style.tsx
src/components/form/inputGroup/InputGroup.tsx

Ajout du `colorPicker` dans le style de l'input group
Transformation, comme prévu, de l'input pour y ajouter un tableau d'actions/icons
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=351)
[Storybook](https://various-improvements--60ca00d41db7ba003be931d8.chromatic.com)

Various improvements on Input and InputGroups

---

CHANGELOG.md
src/components/form/input/Input.tsx

Trompé de type pour bloquer le `onClickActions`
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=354)
[Storybook](https://fix-input-type--60ca00d41db7ba003be931d8.chromatic.com)

Fix input type

---

src/components/form/colorPicker/ColorPicker.stories.tsx
src/components/form/colorPicker/ColorPicker.tsx
src/components/form/colorPicker/enums.ts
src/components/form/colorPicker/index.tsx

New Variant for the color picker input
#366 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=370)
[Storybook](https://366-color-picker-variant--60ca00d41db7ba003be931d8.chromatic.com)

[366] `ColorPicker` Variant

---

src/components/tooltip/Tooltip.stories.tsx
src/styles/theme/index.ts

fix tooltip Z-Index to have tooltips display on top of modals
#381 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=383)
[Storybook](https://381-tooltip-zindex--60ca00d41db7ba003be931d8.chromatic.com)

Fix Tooltip zIndex

---

src/components/button/Button.tsx

Remove console.log

---

src/components/search/Search.stories.tsx
src/components/search/Search.tsx

Je forward la ref sur le compo Search, pour éventuellement tenter d'autofocus dans la modale médiateur
mediateur
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=394)
[Storybook](https://pass-ref-search--60ca00d41db7ba003be931d8.chromatic.com)

Pass ref to search component

---

src/components/Proposal/Proposal.Body.tsx
src/components/Proposal/Proposal.Content.tsx
src/components/Proposal/Proposal.Cover.tsx
src/components/Proposal/Proposal.Footer.tsx
src/components/Proposal/Proposal.Header.Author.tsx
src/components/Proposal/Proposal.stories.tsx
src/components/Proposal/Proposal.tsx

[Fix] - Fix Proposal props and add Status

---

src/components/table/tr/Tr.tsx

set tr verticalAlign to middle

---

CHANGELOG.md
package.json

`2024-06-12`
- 🛠 Refactor Twitter icon by X icon [#422](https://github.com/cap-collectif/ui/pull/422)

1.10.3 (#422)

---

src/components/form/codeInput/CodeInput.tsx

chore: fix typo

---

src/components/toast/ToastContainer.tsx

Add a prop that was missing on toast container
[17198](https://github.com/cap-collectif/platform/issues/17198)
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=433)
[Storybook](https://fix-toast-missing-default-prop--60ca00d41db7ba003be931d8.chromatic.com)

fix: missing prop on toast container

---

src/components/toast/Toast.stories.tsx
src/components/toast/Toast.tsx

- corriger l'affichage des toasts sur mobile
- corriger le onKeyDown (actuellement, n'importe
- ajouter un variant manquant dans les stories
[17248](https://github.com/cap-collectif/platform/issues/17248)
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=442)
[Storybook](https://17248-fix-toast--60ca00d41db7ba003be931d8.chromatic.com)

feat(toast): fix minor accessibility + design issues

---

src/components/form/hour/HourInput.tsx
src/components/form/inputGroup/InputGroup.stories.tsx

Le placeholder n'existe pas sur l'input type "time" donc on le supprime.
Ajout de la date actuelle à la place du placeholder et correction j'espère du souci sur la refonte
https://github.com/cap-collectif/ui/issues/446

fix: remove placeholder + fix defaultValue

---

src/components/form/uploader/Uploader.tsx

Ca plante en prod quand on oublie de passer le type.
https://github.com/cap-collectif/platform/issues/17421
https://github.com/cap-collectif/platform/issues/17390

fix: undefined error

---

src/components/form/codeInput/CodeInput.tsx
src/components/form/date/dateInput/DateInput.tsx
src/components/form/hour/HourInput.tsx

On assignait un id hardcodé identique à chaque instance, donc les id n'étaient pas uniques.
N/A
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=502)
[Storybook](https://remove-fixed-ids--60ca00d41db7ba003be931d8.chromatic.com)

fix: remove hardcoded ids

---

src/components/modal/header/ModalHeader.tsx

set aria-hidden=false to modal close button icon
- #519

set aria-hidden=false to modal close button icon

---

src/components/modal/body/ModalBody.tsx

Suite au retour d'audit du MTE, demande de remplacer la balise main de la modale par une div pour améliorer la structure des pages.
https://github.com/cap-collectif/platform/issues/18332

fix(a11y): modal structure

---

src/components/button/Button.style.ts
src/utils/getThemeWithColorsToken.ts

Ajout du fond blanc sur la variant Tertiary du bouton
#545 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=547)
[Storybook](https://fix-button-tertiary--60ca00d41db7ba003be931d8.chromatic.com)

fix(button): add background color to tertiary variant
