- src/components/form/dateRange/DateRange.stories.tsx
- src/components/form/dateRange/DateRange.tsx
Ajout de 3 nouvelles props disponibles pour le composants : 
- `isOutsideRange`
- `minDate`
- `maxDate`
(Bonus : Correction du typage des props) 
#10
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=223)
[Storybook](https://10-improve-daterange--60ca00d41db7ba003be931d8.chromatic.com)
> [10] Improve DateRange props

- src/components/popover/Popover.tsx
Just a quick fix for the state of `:focus-visible`
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=228)
[Storybook](https://popover-outline-fix--60ca00d41db7ba003be931d8.chromatic.com)
> Fix `Popover`outline when `:focus-visible`

- src/components/form/style.ts
- src/styles/theme/index.ts
The portal in react select must be on top of modals and other stuff
> Adds selectPortal zIndex property

- src/components/modal/Modal.tsx
Correction de la propriété `overflow` sur l'overlay du composant `Modal` 
`overflow: overlay` est deprecated et ne fonctionne pas sur firefox, on le remplace donc par `auto` qui se rapproche le plus du comportement d'`overlay`
https://developer.mozilla.org/fr/docs/Web/CSS/overflow
#176
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=236)
[Storybook](https://176-fix-overflow-overlay--60ca00d41db7ba003be931d8.chromatic.com)
> [176] Fix modal overlay

- src/components/multiStepModal/MultiStepModal.stories.tsx
- src/components/multiStepModal/body/MultiStepModal.Body.tsx
In this repo i change the prop `info` to optional like what we have for `Modal`
NA
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=239)
[Storybook](https://fix-multistepmodal--60ca00d41db7ba003be931d8.chromatic.com)
> Fix `MultiStepModal` info prop

- src/components/multiStepModal/MultiStepModal.tsx
- src/components/multiStepModal/footer/MultiStepModal.Footer.ContinueButton.tsx
- src/components/multiStepModal/index.tsx
`MultiStepModal` pass context actions as props to children
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=254)
[Storybook](https://multi-step-modal-context--60ca00d41db7ba003be931d8.chromatic.com)
> `MultiStepModal` pass context actions as props to children

- src/components/modal/Modal.tsx
Les props `onOpen` / `onClose` ne se déclenchaient pas lorsqu'on ouvrait / fermait la modal.
#58
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=256)
[Storybook](https://58-fix-props--60ca00d41db7ba003be931d8.chromatic.com)
> [58] Fix prop onOpen & onClose

- src/components/form/date/dateInput/DateInput.stories.tsx
- src/components/form/date/dateInput/DateInput.style.tsx
- src/components/form/date/dateInput/DateInput.tsx
Fix the DateInput component to display a single month and changed the navigation arrows to be on the right and the month caption to be on the left (like the spec)
https://www.notion.so/Date-Picker-5308682ea95e481886fdad15b19ba539
#34 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=265)
[Storybook](https://34-fix-dateInput--60ca00d41db7ba003be931d8.chromatic.com)
> single month display and arrows on the right

- src/components/multiStepModal/body/MultiStepModal.Body.tsx
- src/components/multiStepModal/progressBar/MultiStepModal.ProgressBar.tsx
Correction de l'enregistrement des étapes d'une modal multi étape.
**Actuellement**, ça enregistrait que lorsqu'il y avait pas encore d'étapes enregistrés.
Donc lorsqu'on modifiait les children, cela ne se mettait pas à jour.
**Maintenant**, on compare les étapes enregistrés avec les children.
#272
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=276)
[Storybook](https://272-fix-register--60ca00d41db7ba003be931d8.chromatic.com)
> [272] Fix register steps

- src/components/popover/Popover.stories.tsx
- src/components/popover/Popover.tsx
Pass `dialogProps` to Popover directly
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=300)
[Storybook](https://fix-popover--60ca00d41db7ba003be931d8.chromatic.com)
> [Fix] Pass Popover props to Popover

- src/components/modal/Modal.stories.tsx
- src/components/modal/Modal.tsx
- src/components/modal/enums.ts
Ajout du variant `SidePanel` sur la modale - pas grand chose si ce n'est le style injecté qui diffère, le comportement reste celui d'une modale classique
#318 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=322)
[Storybook](https://318-side-panel-modal--60ca00d41db7ba003be931d8.chromatic.com)
> Adds Side Panel variant on Modal component

- src/components/accordion/Accordion.stories.tsx
- src/components/accordion/Accordion.tsx
- src/components/accordion/button/AccordionButton.tsx
- src/components/accordion/enums.ts
- src/components/accordion/item/AccordionItem.tsx
Ajout de la variant transparent sur le composant Accordeon
on enlève le background, on réduit les espacements et on enlève le padding à gauche
https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=330
https://www.chromatic.com/component?appId=60ca00d41db7ba003be931d8&csfId=library-accordion--variant-transparent&buildNumber=625&k=63b7e27478a897d380ecc8a6-1200-interactive-true&h=13&b=-6
> add accordion transparent variant

- src/components/inlineSelect/choice/InlineSelectChoice.tsx
Dans le compo `InlineSelectChoice` le `useHotKeys` bind la touche entrée sur la `Box`, ça créer un conflit avec tous les autres éléments de la page qui peuvent être actionné avec la touche Entrée
Le fonctionnement voulu fonctionne nativement du coup on peut supprimer l'utilisation du hook
> remove useHotkeys in InlineSelect

- src/components/modal/Modal.tsx
- src/components/modal/enums.ts
- src/components/multiStepModal/MultiStepModal.context.tsx
- src/components/multiStepModal/MultiStepModal.stories.tsx
- src/components/multiStepModal/MultiStepModal.tsx
- src/components/multiStepModal/progressBar/MultiStepModalProgressBar.tsx
- src/styles/theme/index.ts
La prop `smoothWorkflow` va rendre la barre d'étape différemment, en y ajoutant au passage un départ à la moitié + 1 . À affiner une fois en test sur des données réelles, mais content pour un premier rendu !
[J'ai fais un exemple assez complet](https://multistepmodal-variant--60ca00d41db7ba003be931d8.chromatic.com/?path=/story/library-multistepmodal--full-screen)
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=378)
[Storybook](https://multistepmodal-variant--60ca00d41db7ba003be931d8.chromatic.com)
> Variant "smoothWorkflow" on multistepmodal

- src/WithCustomTheme.stories.tsx
- src/components/accordion/button/AccordionButton.tsx
- src/components/avatar/Avatar.tsx
- src/components/avatarGroup/AvatarGroup.tsx
- src/components/button/Button.style.ts
- src/components/button/Button.tsx
- src/components/form/checkbox/Checkbox.style.tsx
- src/components/form/checkbox/Checkbox.tsx
- src/components/form/colorPicker/ColorPicker.tsx
- src/components/form/hour/HourInput.tsx
- src/components/form/radio/Radio.style.tsx
- src/components/form/radio/Radio.tsx
- src/components/form/select/AsyncCreatableSelect.tsx
- src/components/form/select/AsyncSelect.tsx
- src/components/form/select/CreatableSelect.tsx
- src/components/form/select/Select.tsx
- src/components/form/style.ts
- src/components/multiStepModal/progressBar/MultiStepModalProgressBar.tsx
- src/components/search/Search.tsx
- src/components/switch/Switch.style.ts
- src/components/switch/Switch.tsx
- src/components/table/td/Td.tsx
- src/styles/modules/colors.ts
- src/utils/color.ts
Pour rendre le DS futur proof, permettre de + facilement y injecter des couleurs.
Historiquement, le DS a été pensé sur une palette de couleur précise -> [Ici ](https://ds.cap-collectif.com/?path=/story/colors--page)
Pour le back office, on est globalement parti sur du bleu, avec du `blue.500` en couleur primaire, qu'on retrouve un peu partout en dur dans le code. Par exemple, le code de style du `<Button />`, actuellement : 
C'est pas optimal, ça laisse aucune possibilité de personnalisation. En plus de ça, pour adapter le DS côté client, on peut pas se limiter à une palette de couleur, puisque certains (la majorité) voudront une charte graphique qui leur est spécifique. J'ai donc ajouté, dans le fichier de couleurs, des valeurs supplémentaires, pour tester un fonctionnement différent : …
> POC - Customisation avancée de la couleur du DS

- src/components/infoMessage/InfoMessage.stories.tsx
- src/components/infoMessage/title/InfoMessageTitle.tsx
Add React.Element type to  InfoMessage.Title for when we use FormattedHTMLMessage
#368 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=384)
[Storybook](https://368-infomessage-title--60ca00d41db7ba003be931d8.chromatic.com)
> Fix InfoMessage.Title to include React Element

- src/components/Tabs/button/TabsButton.tsx
`TabsButton` has a ZIndex of 1 so it's visible under Dialogs
#317
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=392)
[Storybook](https://tabs-z-index--60ca00d41db7ba003be931d8.chromatic.com)
> Fix `TabButton` Z-index

- .eslintrc.js
- .github/workflows/main.yml
- .github/workflows/size.yml
- package.json
- src/@types/reakit-utils/index.d.ts
- src/@types/reakit/index.d.ts
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/buttonList/TabsButtonList.tsx
- src/components/accordion/button/AccordionButton.tsx
- src/components/button/Button.tsx
- src/components/buttonQuickAction/ButtonQuickAction.style.ts
- src/components/dragnDrop/DragnDrop.stories.tsx
- src/components/form/date/Date.style.ts
- src/components/form/date/dateInput/DateInput.tsx
- src/components/form/date/dateRange/DateRange.tsx
- src/components/icon/Icon.tsx
- src/components/inlineSelect/choice/InlineSelectChoice.tsx
- src/components/menu/list/MenuList.tsx
- src/components/modal/Modal.tsx
- src/components/spotIcon/SpotIcon.tsx
- src/components/table/thead/Thead.tsx
- src/components/table/tr/Tr.style.ts
- src/components/toast/Toast.tsx
- src/styles/modules/keyframes.ts
- tsconfig.json
- yarn.lock
Mise à jour de dépendance, je suis pas sur ce que soit ça qui bloque pour react 18 mais c'est fort probable au vu du nombre de messages d'erreur que ça me générait.
On passe donc `styled-components` de la v5 à la v6. Y'a encore quelques soucis de typage, c'est en TODO le temps que ce soit corrigé chez eux.
Au passage, j'ai réparé la github action `size` , et augmenté les versions de typescript et eslint. Ca nous à généré pleins de nouveaux warnings, visible directement dans cette PR d'ailleurs, que je corrigerai dans un prochain ticket ou au fur et à mesure.
Probablement https://github.com/cap-collectif/platform/issues/16208
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=398)
[Storybook](https://upgrade-dependencies--60ca00d41db7ba003be931d8.chro …
> Upgrade styled-components on Design System

- src/components/multiStepModal/MultiStepModal.stories.tsx
- src/components/multiStepModal/body/MultiStepModalBody.tsx
on set l'offset de la transition à 40%, en laissant à 50% le layout shift sur chrome mais pas sur les firefox/safari
j'ajoute un cas dans la story avec le code input
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=430)
[Storybook](https://multistep-modal-body-disable-transition--60ca00d41db7ba003be931d8.chromatic.com)
> MultiStepBody offset 40%

- src/components/toast/Toast.tsx
- src/components/toast/ToastContainer.tsx
[17198](https://github.com/cap-collectif/platform/issues/17198)
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=436)
[Storybook](https://fix-non-disappearing-toast--60ca00d41db7ba003be931d8.chromatic.com)
> fix(toast): onClose, toast hidden still present in DOM

- src/components/toast/ToastContainer.tsx
Dans platform, on utilise <ToastContainer> à plusieurs endroits.
Pour fermer un toast, on devait appeler la fonction onClose autant de fois qu'il existe de <ToastContainer>
[17198](https://github.com/cap-collectif/platform/issues/17198)
> fix(toast): events not working when several instances of ToastContainer exist

- src/components/form/hour/HourInput.stories.tsx
- src/components/form/hour/HourInput.tsx
- src/components/form/inputGroup/InputGroup.stories.tsx
Un bug sur l'input type heure a été repéré sur une branche de `platform`.
Plutôt que de le corriger et maintenir notre custom input type="dateHour", on met à jour pour utiliser le composant html natif `<input type="time" />`
https://github.com/cap-collectif/ui/issues/446
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=447)
[Storybook](https://446-refactor-hour-input--60ca00d41db7ba003be931d8.chromatic.com) 
AVANT :
APRES :
> refactor: replace hour input with html native input type="time"

- src/components/search/Search.tsx
Demande accessibilité IDF
Pas possible d'embarquer `Intl`, donc j'ai ajouté une prop, dont la valeur par défaut est le texte proposé par IDF, à savoir "Supprimer la saisie".
Ajout des roles aria et changement du svg cliquable en un bouton type button également pour l'accessibilité
https://github.com/cap-collectif/platform/issues/17279 
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=449)
[Storybook](https://17279-idf-search-button--60ca00d41db7ba003be931d8.chromatic.com)
> fix(accessibility): make delete text icon a button and add a delete icon label prop, defaulting to french

- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/button/TabsButton.tsx
- src/components/Tabs/panel/TabsPanel.tsx
Quand le contenu du TabPanel est vide, ça rend bizarre.
On veut retirer le bloc s'il est vide, et arrondir les angles du TabButton en conséquence.
Cf les irritants UI notifiés par Sylvain dans les commentaires de cette issue : https://github.com/cap-collectif/platform/issues/17262
> fix: remove tab content if it's empty

- src/components/popover/Popover.tsx
ajoute la possibilité d'override le zIndex de la Popover
le zIndex déjà configuré était sur le mauvais element
> customize Popover zIndex

- src/components/modal/Modal.stories.tsx
- src/components/modal/Modal.tsx
La propriété aria-labelledby ne fonctionnait pas correctement et se retrouvait passée au child de la modale au lieu du parent qui contient le `role="dialog"` et le `aria-modal="true"`
Cf Prio 5 dans ce ticket : https://github.com/cap-collectif/platform/issues/17279
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=458)
[Storybook](https://fix-aria-labelledby-drilling--60ca00d41db7ba003be931d8.chromatic.com)
> fix(accessibility/modal): aria-labelledby not applied properly in modal

- src/components/modal/header/ModalHeader.tsx
- src/components/modal/headerLabel/ModalHeaderLabel.tsx
- src/components/modal/shared.ts
On a un warning sur des dépendances circulaires dans le composant Modal.
Cette PR corrige le souci.
Pas besoin de faire une release, ça sera embarqué dans la prochaine
Pas d'issue créée, juste ce warning au moment du `yarn`
```
⠧ Building modules
Circular dependency: src/components/modal/header/ModalHeader.tsx -> src/components/modal/headerLabel/ModalHeaderLabel.tsx -> src/components/modal/header/ModalHeader.tsx
Circular dependency: src/components/modal/header/ModalHeader.tsx -> src/components/modal/headerLabel/ModalHeaderLabel.tsx -> src/components/modal/header/ModalHeader.tsx
Circular dependency: src/components/modal/header/ModalHeader.tsx -> src/components/modal/hea
✓ Building modules 2.9 mins
✨  Done in 175.52s.
````
> fix: remove circular dependency on modal component

- src/components/form/uploader/Uploader.tsx
Quand on upload un fichier qui n'a pas de propriété url et qu'on change d'onglet (dans une modale par exemple) puis qu'on revient sur l'uploader, la miniature n'est pas conservée puisque la miniature est set seulement si on a une propriété url.
Prendre la valeur de value.path OU value.url
Pas d'issue créée, c'est un souci que j'ai vu en travaillant sur la refonte de la page invitations.
https://github.com/cap-collectif/platform/pull/17251
> fix: thumbnail persistence

- src/components/table/Table.stories.tsx
Ajout d'un variant manquant dans les stories du composant Table.
Lors de la refonte de la page Invitation d'utilisateur·ices dans le BO, on a constaté un bug lors du second clic sur l'en-tête de colonne filtrable, quasiment invisible à cause d'une opacité très faible.
Un ticket a été créé, en attente de priorisation.
Ticket ayant permis d'identifier le souci : https://github.com/cap-collectif/platform/pull/17251 (dans les commentaires de Max dans l'issue liée)
Issue créée : https://github.com/cap-collectif/platform/issues/17500
> feat(Table): add a filterable story to Table component stories

- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/button/TabsButton.tsx
On a un affichage buggy dès lors qu'on a plusieurs TabButtons ou que la largeur de fenêtre est trop petite.
Pas créé d'issue mais on en a parlé plusieurs fois et c'est un méga quick fix.
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=470)
[Storybook](https://fix-tabs-padding--60ca00d41db7ba003be931d8.chromatic.com) 
AVANT :
APRES :
> fix: remove tab button padding

- src/components/table/Table.stories.tsx
A la base c'était une PR pour corriger le souci de filtre dans le TableHead, mais le problème n'est plus constaté dans platform.
Comme j'avais push ce mini fix en passant sur une story, je le mets en PR tant qu'à faire.
N/A
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=471)
[Storybook](https://17500-fix-tablehead-filter--60ca00d41db7ba003be931d8.chromatic.com)
> fix(Table/story): add condition to setState to prevent infinite re-render

- src/components/tabBar/TabBar.stories.tsx
- src/components/tabBar/TabBar.tsx
Ajouter un élément "sideContent" au composant TabBar.
Dans de nouvelles maquettes, le composant contient un élément supplémentaire sur le côté.
https://github.com/cap-collectif/platform/issues/17423
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=476)
[Storybook](https://add-sidecontent-to-tabbar--60ca00d41db7ba003be931d8.chromatic.com)
> feat: add sideContent to TabBar

- src/components/tabBar/TabBar.tsx
- src/components/tabBar/TabHeader.tsx
- src/components/tabBar/pane/TabPane.tsx
La tabbar n'était pas tabbable, donc pas possible de naviguer au clavier.
En lien avec la refonte du BO - page Utilisateur·ices : https://github.com/cap-collectif/platform/issues/17426
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=479)
[Storybook](https://add-tabbable-to-tabbar--60ca00d41db7ba003be931d8.chromatic.com)
> feat(TabBar): add keyboard navigation

- src/components/toast/Toast.stories.tsx
- src/components/toast/Toast.tsx
Lorsqu'on a un toast avec un contenu très long, la largeur n'a pas de maximum.
J'ai corrigé le souci et ajouté une story pour refléter ce cas.
https://github.com/cap-collectif/platform/issues/17699
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=480)
[Storybook](https://17699-fix-toast-width--60ca00d41db7ba003be931d8.chromatic.com) 
AVANT :
APRES :
> fix: toast width

- src/components/tabBar/TabBar.tsx
- src/components/tabBar/TabHeader.tsx
Sylvain a demandé une mise à jour du composant TabBar pour correspondre au design :  
- on remplace le boxShadow par une border-bottom
- on retire le soulignage en bleu d'un onglet hovered (le soulignage bleu est uniquement sur l'onglet actif)
Lié à la refonte de la page sonata des Groupes d'utilisateur·ices https://github.com/cap-collectif/platform/issues/17424#issuecomment-2642584042
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=486)
[Storybook](https://remove-tabbar-box-shadow--60ca00d41db7ba003be931d8.chromatic.com) 
Onglet actif : Agui
Onglet hovered : Alex
Avant : 
Après :
> fix: tabbar design

- .github/pull_request_template.md
- src/components/table/Table.stories.tsx
- src/components/table/td/Td.tsx
The issue was that if the value vas 0 (of type number), the cell was considered empty because children was falsy. Thus returning a dash (placeholder for empty cells)
J'ai ajouté un 0 dans la story Table Default pour qu'on spot plus facilement si régression.
https://github.com/cap-collectif/platform/issues/17750
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=484)
[Storybook](https://fix-minus-zero-table--60ca00d41db7ba003be931d8.chromatic.com)
> fix: 0 on Table that was displaying -0

- src/components/form/uploader/Uploader.stories.tsx
- src/components/form/uploader/Uploader.style.tsx
- src/components/form/uploader/Uploader.tsx
Suite à l'ajout des specs de taille des Uploader, on crée une régression visuelle notamment dans les modales, où on veut que l'Uploader prenne toute la largeur de la modale (sauf en cas de modale trop grande, comme la fullscreen)
Nécessaire suite à la màj de la version du DS dans le ticket de la refonte de la page Groupes d'utilisateur·ices.
Nécessaire également pour éviter une régression sur la page d'invitation des utilisateur·ices
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=488)
[Storybook](https://add-fullwidth-uploader--60ca00d41db7ba003be931d8.chromatic.com) 
Story ajoutée pour visualiser la différence avec / sans `isFullWidth`
> feat: add fullWidth prop to `Uploader`

- .storybook/main.js
- package.json
- yarn.lock
Besoin de màj majeure de Typescript (v4 --> v5)
Nécessaire pour l'ajout de la lib Reakit, elle-même nécessaire pour le chantier Accessibilité.
https://github.com/cap-collectif/platform/issues/18152
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=497)
[Storybook](https://18152-major-typescript-upgrade--60ca00d41db7ba003be931d8.chromatic.com)
> feat: typescript upgrade v4 --> v5

- src/utils/getThemeWithColorsToken.ts
Modification de la couleur de background du compo `ButtonQuickAction`, vu et validé avec Sylvain.
Nécessaire pour la màj du compo ButtonQuickAction dans platform à cause de l'impact sur les composants Carrousel / A la une.
https://github.com/cap-collectif/platform/issues/18036
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=503)
[Storybook](https://add-background-to-btnquickaction--60ca00d41db7ba003be931d8.chromatic.com)
> fix: update btnquickaction bg color

- src/components/tabBar/TabHeader.tsx
Correction du style du TabBar (le `count` --> le "666" dans les captures ci-dessous)
N/A mais retour fait par Max dans un ticket qui traite https://github.com/cap-collectif/platform/issues/17928 partiellement
[Chromatic PR](https://www.chromatic.com/pullrequest?appId=60ca00d41db7ba003be931d8&number=534)
[Storybook](https://tabbar-style--60ca00d41db7ba003be931d8.chromatic.com) 
**AVANT**
**APRES**
> fix(TabBar): style
